name: "Atlas build"
description: "Build Atlas"

inputs:
  build-release:
    description: "Builds release"
    required: false
    default: 'true'
  build-debug:
    description: "Build debug"
    required: false
    default: 'false'
  build-atlas:
    description: "Build atlas"
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Grab dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install build-essential qt6-base-dev libsqlite3-dev libgl1-mesa-dev libglx-dev libqt6charts6-dev -y

    - name: CMake Release
      shell: bash
      if: ${{inputs.build-release == 'true'}}
      run: cmake -S . -B ${{github.workspace}}\builds\build-r -DCMAKE_BUILD_TYPE=Debug

    - name: CMake Debug
      shell: bash
      if: ${{inputs.build-debug == 'true'}}
      run: cmake -S . -B ${{github.workspace}}\builds\build-d -DCMAKE_BUILD_TYPE=Debug

    - name: CMake Debug Release
      shell: bash
      if: ${{inputs.build-release == 'true' && inputs.build-profile == 'true'}}
      run: cmake -S . -B ${{github.workspace}}\builds\build-rp -DCMAKE_BUILD_TYPE=Debug -DATLAS_PROFILE_ENABLE=ON

    - name: Build Target Atlas Release
      shell: bash
      if: ${{inputs.build-release == 'true' && inputs.build-atlas == 'true'}}
      run: |
        cmake --build ${{github.workspace}}\builds\build-r -j8 --target Atlas

    - name: Build Target Atlas Debug
      shell: bash
      if: ${{inputs.build-debug == 'true' && inputs.build-atlas == 'true'}}
      run: |
        cmake --build ${{github.workspace}}\builds\build-d -j8 --target Atlas