name: Release Nightly
on:
  push:
    branches:
      - nightly
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          ref: nightly

      - name: Prepare version string
        run: |
          echo "ATLAS_VERSION_STR=Nightly-$(date +%Y-%m-%d)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          env

      - uses: ./.github/actions/build
        with:
          build-release: false
          build-debug: true
          build-atlas: true
          version-string: ${{ env.ATLAS_VERSION_STR }}

      - name: Package
        run: |
          env
          cd ${{github.workspace}}
          mkdir Atlas-Release
          move ${{github.workspace}}\builds\build-d\bin\* ${{github.workspace}}\Atlas-GameManager-Nightly-Debug\
          7z.exe a -tzip -mm=Deflate -mx=5 ${{github.workspace}}\Atlas-GameManager-${{ env.ATLAS_VERSION_STR }}-Windows.zip ${{github.workspace}}\Atlas-GameManager-Nightly-Debug 

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          tag_name: ${{ env.ATLAS_VERSION_STR }}
          name: ${{ env.ATLAS_VERSION_STR }}
          body: Nightly build of ${{ env.ATLAS_VERSION_STR }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          target_commitish: staging
          files: |
            Atlas-GameManager-${{ env.ATLAS_VERSION_STR }}-Windows.zip