name: Release Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkdate:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should-run: ${{ steps.check_date.outputs.should-run }}
    steps:
      - uses: actions/checkout@v3
      - id: should_run
        continue-on-error: true
        name: Check latest commits
        if: ${{github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{github.sha}} && echo "::set-output name=should_run::false")

  release:
  if: ${{(needs.checkdate.outputs.should-run == 'true') || (github.event_name == 'workflow_dispatch')}}
  runs-on: windows-latest
  needs: checkdate
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: ./.github/actions/build
      with:
        build-release: false
        build-debug: true
        build-atlas: true

    - name: Package
      run: |
        cd ${{github.workspace}}
        mkdir Atlas-Release
        move ${{github.workspace}}\builds\build-d\bin\* ${{github.workspace}}\Atlas-GameManager-Nightly-Debug\
        7z.exe a -tzip -mm=Deflate -mx=5 ${{github.workspace}}\Atlas-GameManager-Nightly-Windows.zip ${{github.workspace}}\Atlas-GameManager-Nightly-Debug

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        tag_name: nightly
        name: Nightly
        body: Nightly build of Atlas-GameManager
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: ${{github.workspace}}\Atlas-GameManager-Nightly-Windows.zip