name: Prerelease Build
on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: Windows-Latest-MinGW
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows-Latest-MinGW",
            os: windows-latest,
            artifact: "windows_mingw.7z",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            archiver: "7z a",
            generators: "Ninja"
          }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          ref: nightly
      - name: Windows
        run:
            choco install ninja cmake
            ninja  --version
            cmake --version
        