name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Extract version
        id: meta
        run: |
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "version_short=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Cache winlibs GCC 12.2
        id: cache-gcc
        uses: actions/cache@v3
        with:
          path: '${{github.workspace}}\mingw64'
          key: ${{runner.os}}-mingw64-gcc-12.2.0

      - name: Download winlibs GCC 12.2
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        uses: carlosperate/download-file-action@v2.0.0
        id: download_gcc
        with:
          file-url: https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-15.0.7-10.0.0-ucrt-r4/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip
          # FUCK    https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.7z
          #                                                                                                              # ITS ALMOST LIKE I HAD THE WRONG VERSION
          file-name: winlibs-gcc.7z
          location: '${{github.workspace}}\mingw64'

      - name: Prepare winlibs GCC 12.2
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        run: |
          cd mingw64
          7z x winlibs-gcc.7z
          cd ..

      - name: Add GCC to PATH
        run: |
          echo "${{github.workspace}}\mingw64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{github.workspace}}\mingw64\mingw64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Cache sqlite
        id: cache-sqlite
        uses: actions/cache@v3
        with:
          path: '${{github.workspace}}\sqlite'
          key: ${{runner.os}}-sqlite-3400100

      - name: Download SQLITE-Amalgamation
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        uses: carlosperate/download-file-action@v2.0.0
        id: download_amalgamation
        with:
          file-url: https://www.sqlite.org/2022/sqlite-amalgamation-3400100.zip
          file-name: sqlite-amalg.zip
          location: '${{github.workspace}}\sqlite'

      - name: Download SQLITE-dll
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        uses: carlosperate/download-file-action@v2.0.0
        id: download_dll
        with:
          file-url: https://www.sqlite.org/2022/sqlite-dll-win64-x64-3400100.zip
          file-name: sqlite-dll.zip
          location: '${{github.workspace}}\sqlite'

      - name: Prepare SQLITE
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        run: |
          cd sqlite
          7z x sqlite-amalg.zip -o"./include"
          cd include/sqlite-amalgamation-3400100
          move * ..
          cd ../..
          7z x sqlite-dll.zip -o"./lib"
          cd ..

      - name: Install Qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.*
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          cache: true

      - name: CMake
        run: |
          cmake -S . -B ${{github.workspace}}\builds\build-r -DCMAKE_BUILD_TYPE=Release -DATLASVERSION='${{env.version_short}}' -DSQL_PATH='${{github.workspace}}\sqlite' -G"MinGW Makefiles"

      - name: Build
        run: |
          cmake --build ${{github.workspace}}\builds\build-r -j8 --target Atlas

      - name: Package
        run: |
          cd ${{github.workspace}}
          mkdir Atlas-Release
          move ${{github.workspace}}\builds\build-r\bin\* ${{github.workspace}}\Atlas-GameManager-Release\
          7z.exe a -tzip -mm=Deflate -mx=5 ${{github.workspace}}\Atlas-GameManager-Windows.zip ${{github.workspace}}\Atlas-GameManager-Release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Extract
          path: ${{github.workspace}}\Atlas-GameManager-Windows.zip
          if-no-files-found: error
          retention-days: 2

  create-release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get artifacts
        uses: actions/download-artifact@v3

      - name: Extract version
        id: meta
        run: |
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "version_short=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Rename
        run: |
          mkdir windows
          mv Windows-Extract\Atlas-GameManager-Windows.zip Atlas-GameManager-${{ env.version_short }}-windows.zip

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Atlas-GameManager-${{env.version_short}}-windows.zip
          

