name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download SQLITE-Amalgamation
        uses: carlosperate/download-file-action@v2.0.0
        id: download_amalgamation
        with:
          file-url: https://www.sqlite.org/2022/sqlite-amalgamation-3400100.zip
          file-name: sqlite-amalg.zip
          location: './sqlite'

      - name: Download SQLITE-dll
        uses: carlosperate/download-file-action@v2.0.0
        id: download_dll
        with:
          file-url: https://www.sqlite.org/2022/sqlite-dll-win64-x64-3400100.zip
          file-name: sqlite-dll.zip
          location: './sqlite'

      - name: Prepare SQLITE
        run: |
          cd sqlite
          7z x sqlite-amalg.zip -o"./include"
          cd include/sqlite-amalgamation-3400100
          move * ..
          cd ../..
          7z x sqlite-dll.zip -o"./lib"
          cd ..

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.2.4
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G"MinGW Makefiles" -DSQL_PATH="./sqlite"

      - name: Build
        run: |
          cd build
          mingw32-make -j8

      - name: Package
        run: |
          cd build/bin
          del Hydrus95_UNIT_TESTS.exe
          cd ..
          mkdir Hydrus95
          move .\bin\* .\Hydrus95\
          7z.exe a -tzip -mm=Deflate -mx=5 ..\Hydrus95-Windows.zip .\Hydrus95

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Extract
          path: Hydrus95-Windows.zip
          if-no-files-found: error
          retention-days: 2

  create-release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get artifacts
        uses: actions/download-artifact@v3

      - name: Extract version
        id: meta
        run: |
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "version_short=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Rename
        run: |
          mkdir windows
          mv Windows-Extract/Hydrus95-Windows.zip Hydrus95-${{ env.version_short }}-windows.zip

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Hydrus95-${{env.version_short}}-windows.zip
          

