name: Test Staging
on:
  push:
    branch:
      staging



jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            build:
              - 'Atlas/src/**'
              - 'Atlas/tests/**'

  build-windows:
    runs-on: windows-latest
    needs: path-filter
    if: ${{ needs.path-filter.outputs.build == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/build
        with:
          build-release: true
          build-debug: false
          build-atlas: false
          build-tests: true

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: Atlas-release-tests
          path: ${{github.workspace}}\builds\build-r\bin
          retention-days: 1

  test:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Download release
        uses: actions/download-artifact@v2
        with:
          name: Atlas-release-tests
          path: ${{github.workspace}}\builds\build-r\bin

      - name: Test-Release
        run: ${{github.workspace}}\builds\build-r\bin\AtlasTESTS.exe

