name: Test Staging
on:
  push:
    branch:
      staging

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/build
        with:
          build-release: true
          build-debug: true
          build-atlas: false
          build-tests: true

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: Atlas-release-tests
          path: ${{github.workspace}}\builds\build-r\bin
          retention-days: 1

  #      - name: Upload debug
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: Atlas-debug-tests
  #          path: ${{github.workspace}}\builds\build-d\bin
  #          retention-days: 1

  test:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Download release
        uses: actions/download-artifact@v2
        with:
          name: Atlas-release-tests
          path: ${{github.workspace}}\builds\build-r\bin

      #      - name: Download debug
      #        uses: actions/download-artifact@v2
      #        with:
      #          name: Atlas-debug-tests
      #          path: ${{github.workspace}}\builds\build-d\bin

      - name: Test-Release
        run: ${{github.workspace}}\builds\build-r\bin\AtlasTESTS.exe

#      - name: Test-Debug
#        run: ${{github.workspace}}\builds\build-d\bin\AtlasTESTS.exe
