name: Prerelease build
on:
  workflow_dispatch:
    push:
      branches: [staging]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download SQLITE-Amalgamation
        uses: carlosperate/download-file-action@v1.1.1
        id: download_amalgamation
        with:
          file-url: https://www.sqlite.org/2022/sqlite-amalgamation-3400100.zip
          file-name: sqlite-amalg.zip
          location: './sqlite'

      - name: Download SQLITE-dll
        uses: carlosperate/download-file-action@v1.1.1
        id: download_dll
        with:
          file-url: https://www.sqlite.org/2022/sqlite-dll-win64-x64-3400100.zip
          file-name: sqlite-dll.zip
          location: './sqlite'

      - name: Prepare SQLITE
        run: |
          cd sqlite
          7z x sqlite-amalg.zip -o"${GITHUB_WORKSPACE}/sqlite/include"
          7z x sqlite-dll.zip -o"${GITHUB_WORKSPACE}/sqlite/lib"
          cd ..

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.2.*

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSQL_PATH=${GITHUB_WORKSPACE}/sqlite -G"MinGW Makefiles" -DQT_PATH=${GITHUB_WORKSPACE}\Qt\6.2.4\mingw_64

      - name: Build
        run: |
          make -j8
