name: Prerelease build
on:
  workflow_dispatch:
    push:
      branches: [staging]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download SQLITE-Amalgamation
        uses: carlosperate/download-file-action@v2.0.0
        id: download_amalgamation
        with:
          file-url: https://www.sqlite.org/2022/sqlite-amalgamation-3400100.zip
          file-name: sqlite-amalg.zip
          location: './sqlite'

      - name: Download SQLITE-dll
        uses: carlosperate/download-file-action@v2.0.0
        id: download_dll
        with:
          file-url: https://www.sqlite.org/2022/sqlite-dll-win64-x64-3400100.zip
          file-name: sqlite-dll.zip
          location: './sqlite'

      - name: Prepare SQLITE
        run: |
          cd sqlite
          7z x sqlite-amalg.zip -o"./temp"
          move ./temp/sqlite-amalgamation-3400100/* ./include/ 
          del temp
          7z x sqlite-dll.zip -o"./lib"
          cd ..

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.2.*
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G"MinGW Makefiles" -DSQL_PATH=./sqlite

      - name: Build
        run: |
          make -j8
