name: Unit tests
on:
  workflow_dispatch:
    push:
      branches: [dev]

jobs:
  ubuntu-tests:
    runs-on: linux-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Run and test
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j8
          ctest ./tests/unit_tests/Hydrus95_UNIT_TESTS
